//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dostava_WPFEntity.Baza
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Artikal//:INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikal()
        {
            this.dostavaArtikalas = new HashSet<dostavaArtikala>();
        }

        public Artikal(int id, string naziv, int? kolicina, float? cena)
        {
            this.id = id;
            this.naziv = naziv;
            this.kolicina = kolicina;
            this.cena = cena;
        }

        public Artikal(Artikal a)
        {
            this.id = a.id;
            this.naziv = a.naziv;
            this.kolicina = a.kolicina;
            this.cena = a.cena;
        }

        public int id{ get; set; }
        public string naziv { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<float> cena { get; set; }




        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dostavaArtikala> dostavaArtikalas { get; set; }




        public override string ToString()
        {
            return id + " " + naziv + " " + kolicina + " " + cena;
        }
    }
}
