//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dostava_WPFEntity.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class dostavaArtikala
    {
        public dostavaArtikala(int id_dostava, int id_artikal, int? kolicina, Artikal artikal, Dostava dostava)
        {
            this.id_dostava = id_dostava;
            this.id_artikal = id_artikal;
            this.kolicina = kolicina;
            Artikal = artikal;
            Dostava = dostava;
        }
        public dostavaArtikala() { }

        public int id_dostava { get; set; }
        public int id_artikal { get; set; }
        public Nullable<int> kolicina { get; set; }
    
        public virtual Artikal Artikal { get; set; }
        public virtual Dostava Dostava { get; set; }



    }
}
