//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dostava_WPFEntity.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostava()
        {
            this.dostavaArtikalas = new HashSet<dostavaArtikala>();
        }

        public Dostava(Dostava d)
        {
            this.id = d.id;
            this.adresaDostave = d.adresaDostave;
            this.datum = d.datum;
        }

        public int id { get; set; }
        public string adresaDostave { get; set; }
        public string datum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dostavaArtikala> dostavaArtikalas { get; set; }
    }
}
